---
groups:
- name: release
  jobs:
  - job-deploy-integration

jobs:
- name: job-deploy-integration
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: resource-bosh-stemcell, trigger: false}
    - {get: resource-bosh-release-redis, trigger: false}
    - get: pipeline
      resource: resource-pipeline
      trigger: false
    - get: resource-pipeline-integration
    - get: release-version
      trigger: false
      resource: resource-release-version
      params: {bump: patch}
  - put: release-version
    resource: resource-release-version
    params: {file: release-version/number}

  # make ./dev2/manifest.yml from templates
  - task: make-manifest
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: pipeline, path: .}
      run: {path: ./integration/bin/make_manifest_and_save.sh}

  - put: resource-bosh-deployment-integration
    params:
      manifest: make-manifest/integration/manifest.yml
      releases:
        - resource-bosh-release-redis/*.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz

  - task: save-deployment-pipeline
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: release-version}
      - {name: make-manifest, path: .}
      - {name: resource-bosh-release-redis}
      - {name: resource-bosh-stemcell}
      run: {path: ./integration/bin/save_deployment_pipeline.sh}

  - put: s3-pipeline-release-candidate
    params:
      from: save-deployment-pipeline/pipeline-assets-(.*).tgz

resources:
- name: resource-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-stemcell-name}}
    version: {{bosh-stemcell-version}}

- name: resource-bosh-release-redis
  type: bosh-io-release
  source: {repository: cloudfoundry-community/redis-boshrelease}

- name: resource-pipeline
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}

- name: resource-pipeline-integration
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}
    paths: [integration/pipeline, integration/templates]

- name: resource-bosh-deployment-integration
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: integration
    ignore_ssl: true

- name: resource-release-version
  type: semver
  source:
    bucket: {{aws-pipeline-bucket}}
    key: release-version
    initial_version: 0.1.0
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: us-east-1

- name: s3-pipeline-release-candidate
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: {{aws-region-name}}
    bucket:  {{aws-pipeline-bucket}}
    private: true
    regexp: pipeline-assets-(.*).tgz
