---
groups:
- name: release
  jobs:
  - job-deploy-integration
  - job-deploy-staging
  - job-deploy-production

jobs:
- name: job-deploy-integration
  public: true
  serial: true
  plan:
  - aggregate:
    - {get: resource-bosh-stemcell, trigger: false}
    - {get: resource-bosh-release-redis, trigger: false}
    - get: pipeline
      resource: resource-pipeline
      trigger: false
    - get: resource-pipeline-integration
    - get: release-version
      trigger: false
      resource: resource-release-version
      params: {bump: patch}
  - put: release-version
    resource: resource-release-version
    params: {file: release-version/number}

  - task: make-manifest
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: pipeline, path: .}
      run: {path: ./integration/bin/make_manifest_and_save.sh}
  - task: git-add
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - name: pipeline
      - name: make-manifest
      run:
        path: ./make-manifest/integration/bin/git-add-all.sh
        args:
          - pipeline
          - "[integration] Update manifest"
  - put: resource-pipeline
    params:
      repository: git-add/make-manifest

  - put: resource-bosh-deployment-integration
    params:
      manifest: make-manifest/integration/manifest.yml
      releases:
        - resource-bosh-release-redis/*.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz

  - task: save-deployment-pipeline
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: release-version}
      - {name: make-manifest, path: .}
      - {name: resource-bosh-release-redis}
      - {name: resource-bosh-stemcell}
      run: {path: ./integration/bin/save_deployment_pipeline.sh}

  - put: s3-pipeline-release-candidate
    params:
      from: save-deployment-pipeline/pipeline-assets-(.*).tgz

- name: job-deploy-staging
  public: true
  serial: true
  plan:
  - aggregate:
    - get: candidate-assets
      resource: s3-pipeline-release-candidate
      passed: [job-deploy-integration]
    - get: resource-pipeline-staging
    - get: pipeline
      resource: resource-pipeline
      trigger: false
      # TODO comment the following when developing this job
      passed: [job-deploy-integration]
    - get: release-version
      resource: resource-release-version
      passed: [job-deploy-integration]
      trigger: false
  - task: unpack-assets
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: pipeline, path: .}
      - {name: candidate-assets}
      run:
        path: ./staging/bin/unpack_assets.sh
        args:
        - candidate-assets/pipeline-assets-*.tgz
        - staging
  - task: make-manifest
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: unpack-assets, path: .}
      run: {path: ./staging/bin/make_manifest_and_save.sh}

  - put: resource-bosh-deployment-staging
    params:
      manifest: make-manifest/staging/manifest.yml
      releases: []
      stemcells: []

- name: job-deploy-production
  public: true
  serial: true
  plan:
  - aggregate:
    - get: candidate-assets
      resource: s3-pipeline-release-candidate
      passed: [job-deploy-staging]
    - get: resource-pipeline-production
    - get: pipeline
      resource: resource-pipeline
      trigger: false
      # TODO uncomment when not developing this job
      # passed: [job-deploy-staging]
    - get: release-version
      resource: resource-release-version
      passed: [job-deploy-staging]
      trigger: false
  - task: unpack-assets
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: pipeline, path: .}
      - {name: candidate-assets}
      run:
        path: ./production/bin/unpack_assets.sh
        args:
        - candidate-assets/pipeline-assets-*.tgz
        - production
  # - task: ls
  #   config:
  #     platform: linux
  #     image: docker:///ubuntu#14.04
  #     inputs:
  #     - {name: unpack-assets, path: .}
  #     run:
  #       path: ls
  #       args: ["-opR", "staging"]
  - task: make-manifest
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - {name: unpack-assets, path: .}
      run: {path: ./production/bin/make_manifest_and_save.sh}

  - put: resource-bosh-deployment-production
    params:
      manifest: make-manifest/production/manifest.yml
      releases: []
      stemcells: []

resources:
- name: resource-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-stemcell-name}}
    version: {{bosh-stemcell-version}}

- name: resource-bosh-release-redis
  type: bosh-io-release
  source: {repository: cloudfoundry-community/redis-boshrelease}

- name: resource-pipeline
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}

- name: resource-pipeline-integration
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}
    paths: [integration/pipeline, integration/templates]

# resource-pipeline-staging should only trigger on pipeline-specific changes
- name: resource-pipeline-staging
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}
    paths: [staging/pipeline]

# resource-pipeline-production should only trigger on pipeline-specific changes
- name: resource-pipeline-production
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}
    paths: [production/pipeline]

- name: resource-bosh-deployment-integration
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: integration
    ignore_ssl: true

- name: resource-bosh-deployment-staging
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: staging
    ignore_ssl: true

- name: resource-bosh-deployment-production
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: production
    ignore_ssl: true

- name: resource-release-version
  type: semver
  source:
    bucket: {{aws-pipeline-bucket}}
    key: release-version
    initial_version: 0.1.0
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: us-east-1

- name: s3-pipeline-release-candidate
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: {{aws-region-name}}
    bucket:  {{aws-pipeline-bucket}}
    private: true
    regexp: pipeline-assets-(.*).tgz
