---
groups:
- name: dev1
  jobs:
  - job-deploy-dev1
- name: dev2
  jobs:
  - job-deploy-dev2
- name: release
  jobs:
  - job-deploy-integration

jobs:
- name: job-deploy-dev1
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-bosh-stemcell
      trigger: false
    - get: resource-bosh-release-redis
      trigger: false
    - get: pipeline
      resource: resource-pipeline
      trigger: false
    - get: resource-pipeline-dev1

  # make ./dev1/manifest.yml from templates
  - task: make-manifest
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - name: pipeline
        path: .
      run:
        path: ./dev1/make_manifest_and_save.sh

  - put: resource-bosh-deployment-dev1
    params:
      manifest: make-manifest/dev1/manifest.yml
      releases:
        - resource-bosh-release-redis/*.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz

- name: job-deploy-dev2
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-bosh-stemcell
      trigger: false
    - get: resource-bosh-release-redis
      trigger: false
    - get: pipeline
      resource: resource-pipeline
      trigger: false
    - get: resource-pipeline-dev2

  # make ./dev2/manifest.yml from templates
  - task: make-manifest
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - name: pipeline
        path: .
      run:
        path: ./dev2/make_manifest_and_save.sh

  - put: resource-bosh-deployment-dev2
    params:
      manifest: make-manifest/dev2/manifest.yml
      releases:
        - resource-bosh-release-redis/*.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz

- name: job-deploy-integration
  public: true
  serial: true
  plan:
  - aggregate:
    - get: resource-bosh-stemcell
      trigger: false
    - get: resource-bosh-release-redis
      trigger: false
    - get: pipeline
      resource: resource-pipeline
      trigger: false
    - get: resource-pipeline-integration
    - get: release-version
      trigger: false
      resource: resource-release-version
      params:
        bump: patch
  - put: release-version
    resource: resource-release-version
    params:
      file: release-version/number

  # make ./dev2/manifest.yml from templates
  - task: make-manifest
    config:
      platform: linux
      image: {{docker-hub-task-image}}
      inputs:
      - name: pipeline
        path: .
      run:
        path: ./integration/make_manifest_and_save.sh

  - put: resource-bosh-deployment-integration
    params:
      manifest: make-manifest/integration/manifest.yml
      releases:
        - resource-bosh-release-redis/*.tgz
      stemcells:
        - resource-bosh-stemcell/*.tgz

resources:
- name: resource-bosh-stemcell
  type: bosh-io-stemcell
  source:
    name: {{bosh-stemcell-name}}
    version: {{bosh-stemcell-version}}

- name: resource-bosh-release-redis
  type: bosh-io-release
  source:
    repository: cloudfoundry-community/redis-boshrelease

- name: resource-pipeline
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}

- name: resource-pipeline-dev1
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}
    paths: [dev1/pipeline, dev1/templates]

- name: resource-pipeline-dev2
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}
    paths: [dev2/pipeline, dev2/templates]

- name: resource-pipeline-integration
  type: git
  source:
    uri: git@github.com:drnic/redis-bosh-pipeline.git
    branch: master
    private_key: {{github-private-key}}
    paths: [integration/pipeline, integration/templates]

- name: resource-bosh-deployment-dev1
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: dev1
    ignore_ssl: true

- name: resource-bosh-deployment-dev2
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: dev2
    ignore_ssl: true

- name: resource-bosh-deployment-integration
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: integration
    ignore_ssl: true

- name: resource-release-version
  type: semver
  source:
    bucket: {{aws-pipeline-bucket}}
    key: release-version
    initial_version: 0.1.0
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    region_name: us-east-1
